In [62]:
import numpy as np
import pandas as pd

In [63]:
vws_dataset = pd.read_parquet(
    "../data/processed/vws_dataset.parquet"
)

In [67]:
vws_dataset.head()

,timestamp,ws100,wd100,ws10,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,i10fg,WIND
0,2018-01-01 00:00:00,12.281535,250.820054,8.888463,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,0.0,13.781487,8673.0
1,2018-01-01 01:00:00,12.115093,248.852093,8.729048,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,0.0,13.967654,8613.0
2,2018-01-01 02:00:00,11.805504,245.666682,8.436531,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,0.0,13.612556,8418.5
3,2018-01-01 03:00:00,11.557783,242.461919,8.252082,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,0.0,12.992998,8299.0
4,2018-01-01 04:00:00,11.096890,239.026854,7.947670,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,0.0,12.466838,8197.5

In [68]:
#wind direction is circular and 359 and 1 degree are same so making sure the model understands
vws_dataset["wd100_sin"] = np.sin(np.radians(vws_dataset["wd100"]))
vws_dataset["wd100_cos"] = np.cos(np.radians(vws_dataset["wd100"]))

vws_dataset["wd10_sin"] = np.sin(np.radians(vws_dataset["wd10"]))
vws_dataset["wd10_cos"] = np.sin(np.radians(vws_dataset["wd10"]))

In [69]:
vws_dataset.head(5)

,timestamp,ws100,wd100,ws10,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,i10fg,WIND,wd100_sin,wd100_cos,wd10_sin,wd10_cos
0,2018-01-01 00:00:00,12.281535,250.820054,8.888463,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,0.0,13.781487,8673.0,-0.944491,-0.328536,-0.279326,-0.279326
1,2018-01-01 01:00:00,12.115093,248.852093,8.729048,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,0.0,13.967654,8613.0,-0.932652,-0.360777,-0.315341,-0.315341
2,2018-01-01 02:00:00,11.805504,245.666682,8.436531,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,0.0,13.612556,8418.5,-0.911164,-0.412044,-0.371450,-0.371450
3,2018-01-01 03:00:00,11.557783,242.461919,8.252082,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,0.0,12.992998,8299.0,-0.886704,-0.462338,-0.424959,-0.424959
4,2018-01-01 04:00:00,11.096890,239.026854,7.947670,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,0.0,12.466838,8197.5,-0.857409,-0.514636,-0.479834,-0.479834

In [70]:
vws_dataset["hour"] = vws_dataset["timestamp"].dt.hour
vws_dataset["day_of_week"] = vws_dataset["timestamp"].dt.dayofweek
vws_dataset["month"] = vws_dataset["timestamp"].dt.month
vws_dataset["day_of_year"] = vws_dataset["timestamp"].dt.dayofyear

In [71]:
vws_dataset["hour_sin"] = np.sin(2*np.pi*vws_dataset["hour"]/24)
vws_dataset["hour_cos"] = np.cos(2*np.pi*vws_dataset["hour"]/24)

vws_dataset["month_sin"] = np.sin(2*np.pi*vws_dataset["month"]/12)
vws_dataset["month_cos"] = np.cos(2*np.pi*vws_dataset["month"]/12)

In [72]:
vws_dataset.head(5)

,timestamp,ws100,wd100,ws10,wd10,wind_shear,relative_humidity,air_density,blh,tcc,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,2018-01-01 00:00:00,12.281535,250.820054,8.888463,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,...,-0.279326,-0.279326,0,0,1,1,0.000000,1.000000,0.5,0.866025
1,2018-01-01 01:00:00,12.115093,248.852093,8.729048,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,...,-0.315341,-0.315341,1,0,1,1,0.258819,0.965926,0.5,0.866025
2,2018-01-01 02:00:00,11.805504,245.666682,8.436531,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,...,-0.371450,-0.371450,2,0,1,1,0.500000,0.866025,0.5,0.866025
3,2018-01-01 03:00:00,11.557783,242.461919,8.252082,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,...,-0.424959,-0.424959,3,0,1,1,0.707107,0.707107,0.5,0.866025
4,2018-01-01 04:00:00,11.096890,239.026854,7.947670,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,...,-0.479834,-0.479834,4,0,1,1,0.866025,0.500000,0.5,0.866025

In [73]:
vws_dataset.drop(columns=["ws10"]) #dropping ws10 because there is high intercorrelation with ws100

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,-0.279326,0,0,1,1,0.000000,1.000000,5.000000e-01,0.866025
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,-0.315341,1,0,1,1,0.258819,0.965926,5.000000e-01,0.866025
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,-0.371450,2,0,1,1,0.500000,0.866025,5.000000e-01,0.866025
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,-0.424959,3,0,1,1,0.707107,0.707107,5.000000e-01,0.866025
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,-0.479834,4,0,1,1,0.866025,0.500000,5.000000e-01,0.866025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70123,2025-12-31 19:00:00,11.614135,273.050549,178.456925,1.443263,82.358868,1.260005,897.876659,0.682255,0.000064,...,0.026928,0.026928,19,2,12,365,-0.965926,0.258819,-2.449294e-16,1.000000
70124,2025-12-31 20:00:00,11.852626,272.359650,179.375989,1.434831,83.138695,1.259141,907.726745,0.648882,0.000096,...,0.010891,0.010891,20,2,12,365,-0.866025,0.500000,-2.449294e-16,1.000000
70125,2025-12-31 21:00:00,12.204287,272.688128,179.124116,1.423274,82.621244,1.258121,912.173354,0.600996,0.000137,...,0.015286,0.015286,21,2,12,365,-0.707107,0.707107,-2.449294e-16,1.000000
70126,2025-12-31 22:00:00,12.575946,274.281331,177.881503,1.420689,82.359252,1.257125,934.792189,0.612354,0.000105,...,0.036966,0.036966,22,2,12,365,-0.500000,0.866025,-2.449294e-16,1.000000
70127,2025-12-31 23:00:00,12.869051,276.649089,175.266215,1.414885,82.118600,1.256178,969.206299,0.604195,0.000083,...,0.082526,0.082526,23,2,12,365,-0.258819,0.965926,-2.449294e-16,1.000000

In [74]:
vws_dataset.to_parquet(
    "../data/processed/featured_data1.parquet",
    index=False
)

In [75]:
vws_dataset.to_csv(
    "../data/processed/featured_data1.csv",
    index=False
)

In [82]:
gradient_data = vws_dataset.copy().drop(columns=["ws10"])

In [83]:
gradient_data.head()

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,-0.279326,0,0,1,1,0.000000,1.000000,0.5,0.866025
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,-0.315341,1,0,1,1,0.258819,0.965926,0.5,0.866025
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,-0.371450,2,0,1,1,0.500000,0.866025,0.5,0.866025
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,-0.424959,3,0,1,1,0.707107,0.707107,0.5,0.866025
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,-0.479834,4,0,1,1,0.866025,0.500000,0.5,0.866025

In [84]:
rnn_data = vws_dataset.copy().drop(columns=["ws10"])

In [85]:
rnn_data.head()

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,-0.279326,0,0,1,1,0.000000,1.000000,0.5,0.866025
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,-0.315341,1,0,1,1,0.258819,0.965926,0.5,0.866025
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,-0.371450,2,0,1,1,0.500000,0.866025,0.5,0.866025
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,-0.424959,3,0,1,1,0.707107,0.707107,0.5,0.866025
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,-0.479834,4,0,1,1,0.866025,0.500000,0.5,0.866025

In [94]:
#creating lag feature for xgboost and light bgm
lag_features = [
    "ws100",
    "wind_shear",
    "i10fg",
    "relative_humidity",
    "air_density",
    "blh",
    "tcc",
    "tp"
]

for col in lag_features:
    gradient_data[f"{col}_lag_1"] = gradient_data[col].shift(1)

    gradient_data[f"{col}_lag_24"] = gradient_data[col].shift(24)

In [96]:
gradient_data.head()

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,relative_humidity_lag_1,relative_humidity_lag_24,air_density_lag_1,air_density_lag_24,blh_lag_1,blh_lag_24,tcc_lag_1,tcc_lag_24,tp_lag_1,tp_lag_24
192,2018-01-09 00:00:00,9.703084,125.489056,308.602216,1.417155,84.670367,1.261920,639.437014,0.925726,0.000010,...,83.489867,75.408284,1.263123,1.290310,652.825194,569.226360,0.917731,0.233086,0.000009,1.373419e-07
193,2018-01-09 01:00:00,9.627024,125.726487,307.303684,1.422310,85.642255,1.260515,621.876571,0.932783,0.000013,...,84.670367,75.457265,1.261920,1.290216,639.437014,575.803520,0.925726,0.221591,0.000010,1.771737e-07
194,2018-01-09 02:00:00,9.633172,125.855338,308.085712,1.426970,86.265424,1.259256,603.635909,0.930667,0.000020,...,85.642255,75.088646,1.260515,1.289881,621.876571,572.804656,0.932783,0.207851,0.000013,1.537921e-07
195,2018-01-09 03:00:00,9.504800,125.967342,295.907953,1.433509,86.639196,1.258307,589.873825,0.928924,0.000024,...,86.265424,74.343305,1.259256,1.289486,603.635909,571.585691,0.930667,0.261382,0.000020,2.836549e-07
196,2018-01-09 04:00:00,9.212879,127.124652,304.846299,1.447067,87.249003,1.257222,570.137648,0.937048,0.000027,...,86.639196,74.309033,1.258307,1.289142,589.873825,575.488294,0.928924,0.312405,0.000024,6.233502e-07

In [86]:
gradient_data["gen_lag_24"] = gradient_data["WIND"].shift(24)

gradient_data["gen_lag_168"] = gradient_data["WIND"].shift(168)

In [88]:
rolling_feature = [
    "ws100",
    "gen_lag_24"
]

for col in rolling_feature:

    gradient_data[f"{col}_roll_mean_6"] = (gradient_data[col].rolling(6).mean())

    gradient_data[f"{col}_roll_mean_24"] = (gradient_data[col].rolling(24).mean())

    gradient_data[f"{col}_roll_std_6"] = (gradient_data[col].rolling(6).std())

    gradient_data[f"{col}_roll_std_24"] = (gradient_data[col].rolling(24).std())

In [95]:
gradient_data = gradient_data.dropna()

In [90]:
gradient_data.head(5)

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,gen_lag_24,gen_lag_168,ws100_roll_mean_6,ws100_roll_mean_24,ws100_roll_std_6,ws100_roll_std_24,gen_lag_24_roll_mean_6,gen_lag_24_roll_mean_24,gen_lag_24_roll_std_6,gen_lag_24_roll_std_24
168,2018-01-08 00:00:00,9.571489,123.458168,203.488319,1.526059,75.408284,1.290310,569.226360,0.233086,1.373419e-07,...,5224.5,8673.0,9.158079,8.100432,0.429500,0.681281,5802.416667,5919.312500,538.974806,899.174680
169,2018-01-08 01:00:00,9.729268,123.341758,203.587791,1.532622,75.457265,1.290216,575.803520,0.221591,1.771737e-07,...,5103.0,8613.0,9.367930,8.178694,0.319738,0.755249,5551.666667,5974.979167,428.074838,795.514429
170,2018-01-08 02:00:00,9.836440,122.082163,210.218073,1.547403,75.088646,1.289881,572.804656,0.207851,1.537921e-07,...,4987.5,8418.5,9.534459,8.259840,0.237768,0.824234,5336.083333,6019.166667,291.115169,700.603136
171,2018-01-08 03:00:00,10.086009,120.790874,208.043154,1.549158,74.343305,1.289486,571.585691,0.261382,2.836549e-07,...,4926.0,8299.0,9.687474,8.353271,0.249817,0.898732,5194.333333,6028.645833,235.534852,683.282542
172,2018-01-08 04:00:00,10.206726,121.037677,196.283602,1.549389,74.309033,1.289142,575.488294,0.312405,6.233502e-07,...,4886.5,8197.5,9.820733,8.456012,0.281620,0.964242,5086.833333,6020.604167,194.486932,695.957051

In [91]:
gradient_data.drop(columns=["timestamp"])

,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,...,gen_lag_24,gen_lag_168,ws100_roll_mean_6,ws100_roll_mean_24,ws100_roll_std_6,ws100_roll_std_24,gen_lag_24_roll_mean_6,gen_lag_24_roll_mean_24,gen_lag_24_roll_std_6,gen_lag_24_roll_std_24
168,9.571489,123.458168,203.488319,1.526059,75.408284,1.290310,569.226360,0.233086,1.373419e-07,0.0,...,5224.5,8673.0,9.158079,8.100432,0.429500,0.681281,5802.416667,5919.312500,538.974806,899.174680
169,9.729268,123.341758,203.587791,1.532622,75.457265,1.290216,575.803520,0.221591,1.771737e-07,0.0,...,5103.0,8613.0,9.367930,8.178694,0.319738,0.755249,5551.666667,5974.979167,428.074838,795.514429
170,9.836440,122.082163,210.218073,1.547403,75.088646,1.289881,572.804656,0.207851,1.537921e-07,0.0,...,4987.5,8418.5,9.534459,8.259840,0.237768,0.824234,5336.083333,6019.166667,291.115169,700.603136
171,10.086009,120.790874,208.043154,1.549158,74.343305,1.289486,571.585691,0.261382,2.836549e-07,0.0,...,4926.0,8299.0,9.687474,8.353271,0.249817,0.898732,5194.333333,6028.645833,235.534852,683.282542
172,10.206726,121.037677,196.283602,1.549389,74.309033,1.289142,575.488294,0.312405,6.233502e-07,0.0,...,4886.5,8197.5,9.820733,8.456012,0.281620,0.964242,5086.833333,6020.604167,194.486932,695.957051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70123,11.614135,273.050549,178.456925,1.443263,82.358868,1.260005,897.876659,0.682255,6.449366e-05,0.0,...,6963.0,10923.5,10.652537,8.338487,0.790154,1.636556,6169.583333,7181.375000,667.670908,1728.387036
70124,11.852626,272.359650,179.375989,1.434831,83.138695,1.259141,907.726745,0.648882,9.629875e-05,0.0,...,7076.0,10730.0,11.031170,8.566818,0.714592,1.729977,6484.166667,7084.562500,546.664949,1662.560645
70125,12.204287,272.688128,179.124116,1.423274,82.621244,1.258121,912.173354,0.600996,1.374891e-04,0.0,...,7254.0,10321.0,11.400567,8.809141,0.635969,1.816731,6713.833333,7003.208333,529.246414,1600.838475
70126,12.575946,274.281331,177.881503,1.420689,82.359252,1.257125,934.792189,0.612354,1.051801e-04,0.0,...,7473.0,10442.5,11.753956,9.075669,0.593557,1.882177,6976.666667,6923.125000,422.730016,1522.124440
70127,12.869051,276.649089,175.266215,1.414885,82.118600,1.256178,969.206299,0.604195,8.318105e-05,0.0,...,7599.0,10577.5,12.078901,9.350741,0.578782,1.935555,7203.500000,6861.562500,292.045716,1459.849146

In [97]:
gradient_data.to_parquet(
    "../data/processed/gradient_data_atm_lag.parquet",
    index=False
)

In [93]:
gradient_data.to_csv(
    "../data/processed/gradient_data.csv",
    index=False
)

In [100]:
rnn_data.head()

,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,0.0,...,-0.279326,-0.279326,0,0,1,1,0.000000,1.000000,0.5,0.866025
1,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,0.0,...,-0.315341,-0.315341,1,0,1,1,0.258819,0.965926,0.5,0.866025
2,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,0.0,...,-0.371450,-0.371450,2,0,1,1,0.500000,0.866025,0.5,0.866025
3,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,0.0,...,-0.424959,-0.424959,3,0,1,1,0.707107,0.707107,0.5,0.866025
4,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,0.0,...,-0.479834,-0.479834,4,0,1,1,0.866025,0.500000,0.5,0.866025

In [99]:
rnn_data = rnn_data.drop(columns=["timestamp"])

In [56]:
rnn_data.head()

,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,0.0,...,-0.279326,-0.279326,0,0,1,1,0.000000,1.000000,0.5,0.866025
1,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,0.0,...,-0.315341,-0.315341,1,0,1,1,0.258819,0.965926,0.5,0.866025
2,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,0.0,...,-0.371450,-0.371450,2,0,1,1,0.500000,0.866025,0.5,0.866025
3,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,0.0,...,-0.424959,-0.424959,3,0,1,1,0.707107,0.707107,0.5,0.866025
4,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,0.0,...,-0.479834,-0.479834,4,0,1,1,0.866025,0.500000,0.5,0.866025

In [101]:
rnn_data.select_dtypes(exclude=["number"])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[70128 rows x 0 columns]

In [102]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_data = pd.DataFrame(
    scaler.fit_transform(rnn_data),
    columns=rnn_data.columns,
    index=rnn_data.index
)

In [103]:
scaled_data

,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,0.515667,0.703012,0.572813,0.056259,0.735995,0.360100,0.478289,0.864849,0.065699,0.0,...,0.360337,0.360337,0.000000,0.000000,0.0,0.00000,0.500000,1.000000,0.75,0.933013
1,0.507834,0.696917,0.579445,0.057451,0.719089,0.367003,0.485738,0.767971,0.040514,0.0,...,0.342330,0.342330,0.043478,0.000000,0.0,0.00000,0.629410,0.982963,0.75,0.933013
2,0.493266,0.687052,0.589950,0.058504,0.705277,0.373349,0.469502,0.635606,0.036394,0.0,...,0.314275,0.314275,0.086957,0.000000,0.0,0.00000,0.750000,0.933013,0.75,0.933013
3,0.481609,0.677127,0.600207,0.059369,0.704086,0.379302,0.446658,0.659038,0.041470,0.0,...,0.287520,0.287520,0.130435,0.000000,0.0,0.00000,0.853553,0.853553,0.75,0.933013
4,0.459920,0.666489,0.611028,0.058975,0.719770,0.384059,0.416972,0.649874,0.037628,0.0,...,0.260083,0.260083,0.173913,0.000000,0.0,0.00000,0.933013,0.750000,0.75,0.933013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70123,0.484260,0.771860,0.518311,0.051466,0.668602,0.654934,0.444201,0.680876,0.031011,0.0,...,0.513464,0.513464,0.826087,0.333333,1.0,0.99726,0.017037,0.629410,0.50,1.000000
70124,0.495483,0.769720,0.521131,0.050279,0.685346,0.648279,0.449306,0.647358,0.046304,0.0,...,0.505445,0.505445,0.869565,0.333333,1.0,0.99726,0.066987,0.750000,0.50,1.000000
70125,0.512032,0.770737,0.520358,0.048652,0.674236,0.640433,0.451611,0.599264,0.066110,0.0,...,0.507643,0.507643,0.913043,0.333333,1.0,0.99726,0.146447,0.853553,0.50,1.000000
70126,0.529521,0.775672,0.516545,0.048288,0.668610,0.632761,0.463333,0.610671,0.050575,0.0,...,0.518483,0.518483,0.956522,0.333333,1.0,0.99726,0.250000,0.933013,0.50,1.000000
70127,0.543314,0.783005,0.508521,0.047471,0.663443,0.625472,0.481169,0.602477,0.039997,0.0,...,0.541263,0.541263,1.000000,0.333333,1.0,0.99726,0.370590,0.982963,0.50,1.000000

In [104]:
rnn_data.to_parquet(
    "../data/processed/rnn_data.parquet"
)

In [107]:
%reset